Global:
  use_gpu: True
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 100
  save_model_dir: /content/drive/MyDrive/rec_r34_vd_none_bilstm_att_128
  save_epoch_step: 
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints: /content/drive/MyDrive/rec_r34_vd_none_bilstm_att_128/latest
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_words/ch/word_1.jpg
  # for data or label process
  character_dict_path: /content/drive/MyDrive/vocab_temp.txt
  character_type: japan
  max_text_length: 32
  infer_mode: False
  use_space_char: True
  save_res_path: /content/drive/MyDrive/predicts_rec_r34_vd_none_bilstm_att_128.txt


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.001
  regularizer:
    name: 'L2'
    factor: 0.00000

Architecture:
  model_type: rec
  algorithm: RARE
  Transform:
  Backbone:
    name: ResNet  
    layers: 34
  Neck:
    name: SequenceEncoder
    encoder_type: rnn 
    hidden_size: 256 #96
  Head:
    name: AttentionHead  # AttentionHead
    hidden_size: 256 
    l2_decay: 0.00001

Loss:
  name: AttentionLoss

PostProcess:
  name: AttnLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /content/data_32x128/short
    label_file_list: ["/content/data_32x128/short/train.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - AttnLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 128]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 128
    drop_last: True
    num_workers: 2

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /content/data_32x128/short
    label_file_list: ["/content/data_32x128/short/test.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - AttnLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 128]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 128
    num_workers: 2